### ISSUE TITLE
How can i allow my wordpress to see authors?

### ISSUE THREAD

**Issue by kennedysmartins** [9d8dev/next-wp#10]
![image](https://github.com/user-attachments/assets/af76394c-465a-45bd-8ef2-f2e396b863a1)

I'm getting **this error** on all the wordpress installations I have, I can access the `/wp-json/wp/v2/users` endpoint **only if I'm logged in**, but as in the application I didn't find any configuration to add **username and password**, I don't know how to proceed

**Comment by kennedysmartins** [comment]
I ended up discovering that it was the "Really Simple SSL" plugin that was blocking this request

**Comment by brijr** [comment]
Amazing! Nice find.
