### ISSUE TITLE
plans on woocommerce?

### ISSUE THREAD

**Issue by akwin1234** [9d8dev/next-wp#11]
Really good work ! thank you soo much.

any plans on woocommerce? ecommerce based project using same concept

**Comment by volfadar** [comment]
i hope i can contribute in this area, i spend 70% of my time in woocommerce, react, and sometimes Next JS. maybe start with a discord group will be a much better step.

**Comment by akwin1234** [comment]
> i hope i can contribute in this area, i spend 70% of my time in woocommerce, react, and sometimes Next JS. maybe start with a discord group will be a much better step.

i have good experience with woocommerce but no experience in react or next js. not sure i would be of any use sadly.

**Comment by volfadar** [comment]
> > i hope i can contribute in this area, i spend 70% of my time in woocommerce, react, and sometimes Next JS. maybe start with a discord group will be a much better step.
> 
> i have good experience with woocommerce/php but no experience in react or next js. not sure i would be of any use sadly.

Haha, actually I didn’t mean to talk to you directly, I just wanted to get my wishes out there and hope the repo authors see this thread. Anyway, this repo is specifically for Next.js or React apps. Why are you asking for a feature in the repo if you haven’t used the framework yet?

**Comment by akwin1234** [comment]
> > > i hope i can contribute in this area, i spend 70% of my time in woocommerce, react, and sometimes Next JS. maybe start with a discord group will be a much better step.
> > 
> > 
> > i have good experience with woocommerce/php but no experience in react or next js. not sure i would be of any use sadly.
> 
> Haha, actually I didn’t mean to talk to you directly, I just wanted to get my wishes out there and hope the repo authors see this thread. Anyway, this repo is specifically for Next.js or React apps. Why are you asking for a feature in the repo if you haven’t used the framework yet?

just happen to be in need after doing a lot of research this seems best approach for me right now

**Comment by youngbloodcyb** [comment]
We currently don't have any plans on woocommerce but we'd love to see where others take this project! 

@brijr and I are not very familiar with building solutions for woocommerce but recognize this is a huge space.

**Comment by akwin1234** [comment]
> We currently don't have any plans on woocommerce but we'd love to see where others take this project!
> 
> @brijr and I are not very familiar with building solutions for woocommerce but recognize this is a huge space.

All good :) Loved your project!
