### ISSUE TITLE
Not Fetching All Categories & All Posts

### ISSUE THREAD

**Issue by Aiman-Shafi** [9d8dev/next-wp#15]
I'm having issues with fetching all the posts and also categories as well. How can I handle the issues?

**Comment by brijr** [comment]
Please give more information.

**Comment by francesco-sommaruga** [comment]
I'having the same problem, it looks like a caching problem in next js. I tried specifying the revalidate in the pages, but did not work. They only way i got it to work is by disabling cache altogheter by forcing it in the fetch function 

`async function fetchWithNoCache(url: string): Promise<Response> {
  const timestamp = new Date().getTime();
  const urlWithTimestamp = `${url}${url.includes('?') ? '&' : '?'}_=${timestamp}`;
  return fetch(urlWithTimestamp, {
    cache: 'no-store',
    headers: {
      'Cache-Control': 'no-cache, no-store, must-revalidate',
      'Pragma': 'no-cache',
      'Expires': '0',
    },
  });
}`

**Comment by notandigg** [comment]
Yes I have been having a lot of issues which I think could be related to cache bugs. Where did you put this code?, would like to try it out to see if it fixes the random errors

**Comment by francesco-sommaruga** [comment]
Just put the function in @/lib/wordpress then call fetchWithNoCache instead of fetch in every endpoint call in the same file. Keep in mind that preventing the content to be cached will turn off ISR, so the endpoints will be hit on every page view

**Comment by notandigg** [comment]
Thank you for the info Francesco.
I have been dealing with a lot of random errors for some days now. But now I managed to find the problem. It was a php error in functions.php 🙂 I’m going to have an eye on it. So this seems to had nothing to do with cache bug. Fingers crossed.
