### ISSUE TITLE
Miscellaneous Feature request: Nice to haves that would be helpful

### ISSUE THREAD

**Issue by hirajanwin** [9d8dev/next-wp#16]
Thanks for adding my earlier request for sitemap! 🙏 

It'd be great to get Table of Contents support for the articles

Youtube Lite embed support that's discussed here https://developer.chrome.com/docs/lighthouse/performance/third-party-facades/

Json LD support for different section like posts, author pages, category pages

**Comment by brijr** [comment]
I consider these add ons and nice to have but not looking to add these in currently. Cheers.
