### ISSUE TITLE
Selecting an author in the filters seems to click the article below it.

### ISSUE THREAD

**Issue by nuotsu** [9d8dev/next-wp#2]
Tapping on an author in the filter dropdown actually triggers a click on the article below it, navigating to the actual article instead of filtering on page.

Noticed this happening on an iPad

![WordpressNext js Starter by 9d8](https://github.com/9d8dev/next-wp/assets/24799299/1b778464-3387-45f0-a2ad-901d038cf3d9)

Awesome work btw

**Comment by youngbloodcyb** [comment]
Thanks for opening this. We'll take a look !

**Comment by youngbloodcyb** [comment]
looking into this further and it looks like its a radix issue.
