### ISSUE TITLE
No images render on Post cards in Posts section 

### ISSUE THREAD

**Issue by FuturisticWizard** [9d8dev/next-wp#24]
No image on Post card in Posts section.  Even though I have a featured image in every Post , it seems to dont see the source url...
```
post:  {
  id: 85,
  date: '2024-10-02T05:12:45',
  date_gmt: '2024-10-02T03:12:45',
  guid: { rendered: 'http://192.168.0.87:8080/?p=85' },
  modified: '2024-10-13T14:36:18',
  modified_gmt: '2024-10-13T12:36:18',
  slug: 'post-4',
  status: 'publish',
  type: 'post',
  link: 'http://192.168.0.87:8080/post-4/',
  title: { rendered: 'Post 4' },
  content: { rendered: '', protected: false },
  excerpt: { rendered: '', protected: false },
  author: 1,
  featured_media: 74,
  comment_status: 'open',
  ping_status: 'open',
  sticky: false,
  template: '',
  format: 'standard',
  meta: { footnotes: '' },
  categories: [ 1, 98 ],
  tags: [],
  class_list: [
    'post-85',
    'post',
    'type-post',
    'status-publish',
    'format-standard',
    'has-post-thumbnail',
    'hentry',
    'category-bez-kategorii',
    'category-solidity'
  ],
  _links: {
    self: [ [Object] ],
    collection: [ [Object] ],
    about: [ [Object] ],
    author: [ [Object] ],
    replies: [ [Object] ],
    'version-history': [ [Object] ],
    'predecessor-version': [ [Object] ],
    'wp:featuredmedia': [ [Object] ],
    'wp:attachment': [ [Object] ],
    'wp:term': [ [Object], [Object] ],
    curies: [ [Object] ]
  }
}
```
![Zrzut ekranu 2024-10-14 181413](https://github.com/user-attachments/assets/6bb5eaea-5aea-43ad-a738-a6ac7c7fbbe5)

**Comment by dotto95** [comment]
Did you add your host to next.config?
https://nextjs.org/docs/messages/next-image-unconfigured-host

**Comment by pcteilor** [comment]
Same problem, but by default of the template it's already set and still no image rendered on page post.

`/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: process.env.WORDPRESS_HOSTNAME,
        port: "",
        pathname: "/**",
      },
    ],
  },
};

export default nextConfig;`

**Comment by pcteilor** [comment]
> Same problem, but by default of the template it's already set and still no image rendered on page post.
> 
> My **next.config.mjs**
> 
> ```
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   images: {
>     remotePatterns: [
>       {
>         protocol: "https",
>         hostname: process.env.WORDPRESS_HOSTNAME,
>         port: "",
>         pathname: "/**",
>       },
>     ],
>   },
> };
> 
> export default nextConfig;
> ```

I change my protocol to "http" and works for me in local development.

**Comment by brijr** [comment]
> > Same problem, but by default of the template it's already set and still no image rendered on page post.
> > My **next.config.mjs**
> > ```
> > /** @type {import('next').NextConfig} */
> > const nextConfig = {
> >   images: {
> >     remotePatterns: [
> >       {
> >         protocol: "https",
> >         hostname: process.env.WORDPRESS_HOSTNAME,
> >         port: "",
> >         pathname: "/**",
> >       },
> >     ],
> >   },
> > };
> > 
> > export default nextConfig;
> > ```
> 
> I change my protocol to "http" and works for me in local development.
> 
> ```
> /** @type {import('next').NextConfig} */
> const nextConfig = {
>   images: {
>     remotePatterns: [
>       {
>         protocol: "http",
>         hostname: process.env.WORDPRESS_HOSTNAME,
>         port: "",
>         pathname: "/**",
>       },
>     ],
>   },
> };
> 
> export default nextConfig;
> ```

Cheers thanks for figuring this out @pcteilor
