### ISSUE TITLE
using MDX instead of WordPress

### ISSUE THREAD

**Issue by leonardobetti** [9d8dev/next-wp#26]
folks I sent an e-mail but I believe you guys rather use github instead. 
so, I don’t have a WordPress blog to import posts or pages. I’d like to use .mdx files within the folders instead of connecting to a WordPress site for data. is there a way to set this up? if possible, could you provide some steps to guide on how to do this? thanks in advance

**Comment by brijr** [comment]
Hey Leonardo! 

Thanks for the kind words in the email. 

If you are wanting to use Markdown/MDX as your blog I would recommend going a different way. It would take a complete overhaul of next-wp to make it work for your usecase. 

Here are some other repos to check out: 

- [Nextra Blog Theme](https://nextra.site/docs/blog-theme/start) -- Very robust
- [MDX Starter by mer](https://mdx.bridger.to/) -- Very simple
- [Another Blog Starter](https://github.com/ChangoMan/nextjs-mdx-blog) -- Another one
