### ISSUE TITLE
The filters are not preserved when using the pagination

### ISSUE THREAD

**Issue by alonsourena** [9d8dev/next-wp#3]
Hi, love this repo ❤️

I found and issue when filtering posts by category, and then using the pagination.

**How to reproduce:**

1) Go to posts
2) Filter by category
3) Go to the next page

The url go to the next page, but it does not preserve the category filter

**Comment by youngbloodcyb** [comment]
thanks for bringin this up, i'm going hop in and work on this today

**Comment by youngbloodcyb** [comment]
<img width="1019" alt="Screenshot 2024-06-17 at 9 35 45 AM" src="https://github.com/9d8dev/next-wp/assets/95453018/c9849a0b-6cf0-47cc-bd80-1484183ffa3a">

Found another issue: `next` btn isn't disable when there aren't any articles remaining. Going to combine this issue into this one and do a PR to address both of these.

**Comment by youngbloodcyb** [comment]
closed w/ https://github.com/9d8dev/next-wp/pull/6
